version: "3.8"

services:
  # PostgreSQL Database
  yuvoi-postgres:
    image: postgres:17
    container_name: yuvoi-postgres
    volumes:
      - ./env/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    networks:
      - app_network
    restart: always

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
